/// <reference types="vite/client" />

// The geokit WASM package is generated by wasm-pack into ../../packages/geo-engine/pkg.
// Its own .d.ts ships in that folder; this ambient decl keeps tsc happy if it's not built yet.
declare module "geokit";
